Q&A/ask/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('athreg.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Q&A/athreg/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views



urlpatterns = [
    path('',views.home, name="home"),

    path('register/',views.registerPage, name="register"),
    path('login/',views.loginPage, name="login"),
    path('logout/',views.logoutUser, name="logout"),
    path('detail/<int:id>',views.detail,name='detail'),
    path('save-comment',views.save_comment,name='save-comment'),
    path('save-upvote',views.save_upvote,name='save-upvote'),
    path('save-downvote',views.save_downvote,name='save-downvote'),
    path('ask-question',views.ask_form,name='ask-question'),
    path('tag/<str:tag>',views.tag,name='tag'),
    path('tags/',views.tags,name='tags'),

    path('profile/',views.profile,name='profile'),
    path('profileinfo/',views.profileinfo,name='profileinfo'),
    path('otheruser/<str:name>',views.otheruser,name='otheruser'),
    path('reset_password/',
     auth_views.PasswordResetView.as_view(template_name="password_reset.html"),
     name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"), 
     name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"), 
        name="password_reset_complete"),

]

Q&A/athreg/models.py
from django.db import models
from django.contrib.auth.models import User,AbstractBaseUser
from django.db.models.signals import post_save
from django.dispatch import receiver






class UserProfile(models.Model):
    user=models.OneToOneField(User,null=True,blank=True,on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=20, null=True)
    email = models.CharField(max_length=50, null=True)
    address = models.CharField(max_length=200, null=True)
    profile_pic = models.ImageField(default = 'default.png',null=True,blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return f'{self.user.username} Profile'

# Question Model
class Question(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    q_title=models.CharField(max_length=300)
    detail=models.TextField()
    tags=models.TextField(default='')
    add_time=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.q_title

# Answer Model
class Answer(models.Model):
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    detail=models.TextField()
    add_time=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.detail

# Comment
class Comment(models.Model):
    answer=models.ForeignKey(Answer,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='comment_user')
    comment=models.TextField(default='')
    add_time=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment

# UpVotes
class UpVote(models.Model):
    answer=models.ForeignKey(Answer,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='upvote_user')

# DownVotes
class DownVote(models.Model):
    answer=models.ForeignKey(Answer,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='downvote_user')

Q&A/athreg/forms.py
from django.forms import ModelForm, fields, widgets
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import *

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class AnswerForm(ModelForm):
    class Meta:
        model=Answer
        fields=('detail',)

        widgets={
            'detail': forms.TextInput(attrs={'class': 'form-control','placeholder':'Write Answer...'}),
        }

class QuestionForm(ModelForm):
    class Meta:
        model=Question
        fields=('q_title','detail','tags')

        widgets={
            'q_title': forms.TextInput(attrs={'class': 'form-control','placeholder':'Question Title...'}),
            'detail': forms.TextInput(attrs={'class': 'form-control','placeholder':'Question Detail...'}),
            'tags': forms.TextInput(attrs={'class': 'form-control','placeholder':'Question Related Tags...'}),
        }

class ProfileForm(ModelForm):
    class Meta:
        model=UserProfile
        fields='__all__'
        exclude = ['user']
        widgets={
            'name': forms.TextInput(attrs={'class': 'form-control','placeholder':'Name...'}),
            'phone': forms.TextInput(attrs={'class': 'form-control','placeholder':'Phone Number...'}),
            'email': forms.TextInput(attrs={'class': 'form-control','placeholder':'Email...'}),
            'address': forms.TextInput(attrs={'class': 'form-control','placeholder':'Adress...'}),
        }

Q&A/athreg/views.py
from django.forms.fields import DateTimeField
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.http import JsonResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from .models import *
from .forms import *
from django.core.paginator import Paginator
from django.utils.datastructures import MultiValueDictKeyError
from django.shortcuts import render,HttpResponse
from django.http import JsonResponse
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Count





# Create your views here.

def registerPage(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:
        form = CreateUserForm()


        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                user=form.save()
                username = form.cleaned_data.get('username')
                UserProfile.objects.create(
                    user=user,
                    name=user.username,
                    email=user.eamil,
                )
                messages.success(request, 'Account has been created for '+ username)
                return redirect('home')

        context = {'form':form}
        return render(request, 'register.html', context)

def loginPage(request):
    if request.user.is_authenticated:
        return redirect('home')
    
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                messages.info(request, 'Username OR Password is incorrect')
        context = {}
        return render(request, 'login.html', context) 

def logoutUser(request):
    logout(request)
    return redirect('login')

    

@login_required(login_url='login')
def home(request):
    if 'q' in request.GET:
        q=request.GET['q']
        quests=Question.objects.annotate(total_comments=Count('answer__comment')).filter(q_title__icontains=q).order_by('-add_time')
    else:
        quests=Question.objects.annotate(total_comments=Count('answer__comment')).all().order_by('-add_time')
    paginator=Paginator(quests,5)
    page_num=request.GET.get('page',1)
    quests=paginator.page(page_num)
    return render(request,'main.html',{"quests":quests})

@login_required(login_url='login')
def detail(request,id):
    quest=Question.objects.get(pk=id)
    tags=quest.tags.split(',')
    answers=Answer.objects.filter(question=quest).order_by('add_time')
    answerform=AnswerForm
    if request.method=='POST':
        answerData=AnswerForm(request.POST)
        if answerData.is_valid():
            answer=answerData.save(commit=False)
            answer.question=quest
            answer.user=request.user
            answer.save()
            messages.success(request,'Answer has been submitted.')


    return render(request,'detail.html',{'quest':quest,
                                        'tags':tags,
                                        'answers':answers,
                                        'answerform':answerform
                                        })

@login_required(login_url='login')
def save_comment(request):
    if request.method=='POST':
        comment = request.POST.get('comment')
        answerid = request.POST.get('answerid')
        answer=Answer.objects.get(pk=answerid)
        user=request.user
        Comment.objects.create(
            answer=answer,
            user=user,
            comment=comment
        )
        return JsonResponse({'bool':True})

def save_upvote(request):
    if request.method=='POST':
        answerid = request.POST.get('answerid')
        answer=Answer.objects.get(pk=answerid)
        user=request.user
        check=UpVote.objects.filter(answer=answer,user=user).count()
        if check>0:
            return JsonResponse({'bool':False})
        else:
            UpVote.objects.create(
                answer=answer,
                user=user
            )
            return JsonResponse({'bool':True})

def save_downvote(request):
    if request.method=='POST':
        answerid = request.POST.get('answerid')
        answer=Answer.objects.get(pk=answerid)
        user=request.user
        check=DownVote.objects.filter(answer=answer,user=user).count()
        if check > 0:
            return JsonResponse({'bool':False})
        else:
            DownVote.objects.create(
                answer=answer,
                user=user
            )
            return JsonResponse({'bool':True})

@login_required(login_url='login')
def ask_form(request):
    form=QuestionForm
    if request.method=='POST':
        questForm=QuestionForm(request.POST)
        if questForm.is_valid():
            questForm=questForm.save(commit=False)
            questForm.user=request.user
            questForm.save()
            messages.success(request,'Question has been added.')
    return render(request,'askques.html',{'form':form})


def tag(request,tag):
    quests=Question.objects.annotate(total_comments=Count('answer__comment')).filter(tags__icontains=tag).order_by('-id')
    paginator=Paginator(quests,10)
    page_num=request.GET.get('page',1)
    quests=paginator.page(page_num)
    return render(request,'tag.html',{'quests':quests,'tag':tag})

@login_required(login_url='login')
def profile(request):
	user = request.user.userprofile
	form = ProfileForm(instance=user)

	if request.method == 'POST':
		form = ProfileForm(request.POST, request.FILES,instance=user)
		if form.is_valid():
			form.save()


	context = {'form':form}
	return render(request, 'profile.html', context)

@login_required(login_url='login')
def profileinfo(request):
    quests=Question.objects.filter(user=request.user).order_by('-id')
    answers=Answer.objects.filter(user=request.user).order_by('-id')
    comments=Comment.objects.filter(user=request.user).order_by('-id')
    upvotes=UpVote.objects.filter(user=request.user).order_by('-id')
    downvotes=DownVote.objects.filter(user=request.user).order_by('-id')
    return render(request,'profileinfo.html',{
        'quests':quests,
        'answers':answers,
        'comments':comments,
        'upvotes':upvotes,
        'downvotes':downvotes,
    })

@login_required(login_url='login')
def tags(request):
    quests=Question.objects.all()
    tags=[]
    for quest in quests:
        qtags=[tag.strip() for tag in quest.tags.split(',')]
        for tag in qtags:
            if tag not in tags:
                tags.append(tag)
    # Fetch Questions
    tag_with_count=[]
    for tag in tags:
        tag_data={
            'name':tag,
            'count':Question.objects.filter(tags__icontains=tag).count()
        }
        tag_with_count.append(tag_data)
    return render(request,'tags.html',{'tags':tag_with_count})

def otheruser(request,name):
    userinfo = UserProfile.objects.filter(name=name)
    if name == request.user.username:
        return render(request,'profileinfo.html')
    else:
        return render(request,'otheruser.html',{'otheruser':userinfo})

Q&A/athreg/templates/askques.html
{% extends 'base.html' %}
{% block title %}Ask Question{% endblock %}
{% block content %}
<div class="container">
    <div class="card mt-5">
        <h5 class="card-header">Ask Question</h5>
        <div class="card-body">
            <form method="post" name="askquesform">
                <div class="form-group">
                    {% csrf_token %}
                    <table class="table table-bordered">
                    {{form.as_table}}
                    <tr>
                        <td colspan="2">
                            <button class="btn btn-dark " onclick="submitform()">Submit</button>
                        </td>
                    </tr>
                </table>
                </div>
                
            </form>
        </div>
    </div>
</div>
<script>
    function submitform(){
        var frm = document.getElementsByName('askquesform')[0];
        frm.submit();
        frm.reset();
        return false;
    }
    if ( window.history.replaceState ) {
        window.history.replaceState( null, null, window.location.href );
    }
</script>
{% endblock %}

Q&A/athreg/templates/base.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}Detail Page{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
  <link rel="stylesheet" href="% static '/animatecss/animate.min.css' %">
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
  <script src="{% static 'bootstrap.min.js' %}"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</head>
<style>
    body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #E5E7E9 !important;
		}
  a:link {
    color: #0c1b2a;
    background-color: transparent;
    text-decoration: none;
  }
  a:visited {
    color: #0c1b2a ;
    background-color: transparent;
    text-decoration: none;
  }
  a:hover {
    color: #1A5276;
    background-color: transparent;
    text-decoration: underline;
  }
	.profile-pic{
		max-width: 200px;
		max-height:200px;
		margin: 0 auto;
		border-radius: 50%;
	}
</style>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><img src="https://images.vexels.com/media/users/3/152347/isolated/preview/27304b9b14ce9bd8a28ca637ed92070e-blue-circle-question-mark-icon-by-vexels.png" alt="" width="35" height="30" class="d-inline-block align-text-top">
        Q&A</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
       
        <ul class="navbar-nav" >
            <li class="nav-item active ">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'ask-question' %}">Ask</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/tags/">Tags</a>
            </li>
        </ul>
        <form class="ms-auto" action="/">
            <div class="input-group">
              <input type="text" name="q" class="form-control" placeholder="Search" />
            <button class="btn btn-secondary" type="submit" id="button-addon2">Search</button>
          </div>
        </form>
        <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link" href="/profileinfo/">{{request.user}}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
          </ul>
      </div>
    </div> 
  </nav>

  <div class="container-md py-4">  
      <div class="row">
        <div class="col-md-6 offset-2">
          
        </div>
      </div>  
  </div>
  
  {% block content %}
    {% endblock %}
    <hr>
    
</body>
</html>

Q&A/athreg/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block title %}{{quest.q_title}}{% endblock %}
{% block content %}
<!-- Question view -->
  <div class="container-md">
    <h2 class="card-header my-top"><b>{{quest.q_title}}</b></h2>
    <p class="mt-1 p-2">{{quest.detail}}</p>
    <p>
        <span class="me-4"></span>
        <span class="badge badge-secondary"><i class="fas fa-user ml-1"></i>&nbsp<a href="/otheruser/{{quest.user.username}}" class="mr-2 text-light"> {{quest.user.username}}</a></span>
        <span class="mr-2 badge badge-success">{{quest.answer_set.count}} Answers</span>
        
        
        
    </p>
    <p>
        Tags:
            {% for tag in tags %}
            <a href="/tag/{{tag|slugify}}"><span class="badge badge-secondary">{{tag}}</span></a>
            {% endfor %}
    </p>
    <p class="card-footer"><span class="me-4">{{quest.add_time|naturaltime}}</span></p>
    <hr>


    <!-- Adding Answer to the question -->
    <div>
        <button type="button" class="btn btn-dark" onclick="show()">Add Answer</button>
    </div>
    <div class="card my-3 col-12 p-0 " id="answ" style="display: none; background-color: transparent; border: black ;" >
        <form method="post" name="ansquesform">
            <div class="form-group">
                {% csrf_token %}
                <table class="table table-bordered">
                    {{answerform.as_table}}
                    <tr >
                        <td colspan="2">
                            <input type="submit" style="margin-left: 50%" class="btn btn-dark mb-lg-auto " onclick="submitformans()" />
                        </td>
                    </tr>
                </table>
            </div>
            
        </form>
    </div>
    
    {% for answer in answers %}
    <div class="row">
        <!-- Upvote and downvote -->
        <div class="col-1" >
            <div class="upvote mt-4" style="margin-left: 50%">
                <strong class="upvote-count-{{answer.id}}">&nbsp&nbsp{{answer.upvote_set.count}}</strong><br>
                <span class="text-dark">
                    <i  class="fa fa-chevron-up fa-2x  upvote-click" data-answer="{{answer.id}}"></i>
                </span>
            </div>
            <div class="downvote mt-3" style="margin-left: 50%">
                <span class="text-dark">
                    <i class="fa fa-chevron-down fa-2x downvote-click" data-answer="{{answer.id}}"></i>
                </span><br>
                <strong class="downvote-count-{{answer.id}}">&nbsp&nbsp{{answer.downvote_set.count}}</strong>
            </div>
        </div>
        <!-- Answer showing -->
        <div class="col-11">
            <div class="card my-3 pb-0">
                <h6 class="card-header">Answer</h6>
                <div class="card-body pb-0">
                    <div class="card-body py-1 border-dark">
                        <p>
                            {{ answer.detail }}
                        </p>
                        <p>
            
                            <span class="badge badge-secondary"><i class="fas fa-user ml-1"></i>&nbsp<a href="/otheruser/{{answer.user.username}}" class="mr-2 text-light"> {{answer.user.username}}</a></span>
                
                            
                        </p>
                    </div>
                    
                    <p class="card-footer pb-0"><span>{{answer.add_time|naturaltime}}</span></p>
                </div>
                
            </div>
            <!-- Comment showing -->
            <div class="row">
                <div class="col-1">

                </div>
                <div class="col-11 pb-0">
                    <div class="card my-3 pb-0">
                        <div class="card-header">Comments <span class="mx-2"></span><span class="comment-count-{{answer.id}}"><span class="mr-2 badge badge-warning">{{answer.comment_set.count}} comments</span></span></div>
                        <div class="card-body pb-0">
                            <div class="comment-wrapper-{{answer.id}}">
                                
                                {% for comment in answer.comment_set.all %}
                                <div class="card mb-2 pb-0">
                                    <div class="card-body py-1">
                                        <p>{{comment.comment}}</p>
                                        <p></p><span class="badge badge-secondary"><i class="fas fa-user ml-1"></i>&nbsp<a href="/otheruser/{{comment.user.username}}" class="mr-2 text-light"> {{comment.user.username}}</a></span>
                    
                                        </p>
                                        
                                    </div>
                                </div>
                                <p class="card-footer p-0"><span>{{comment.add_time|naturaltime}}</span></p>
                                {% endfor %}
                            </div>
                        </div>
                        
                        
                    </div>
                </div>

            </div>
            
            

            <!-- Adding comment -->

            <div class="card my-3">
                <h6 class="card-header">Add Comment</h6>
                <div class="card-body">
                    <textarea class="form-control comment-text-{{answer.id}}"></textarea>
                    <button type="button" data-answer="{{answer.id}}" class="btn btn-dark my-3 save-comment">Submit</button>
                </div>
            </div>
        </div>
    </div>
    {% csrf_token %}
    {% endfor %}

    
    
  </div>
  
  <script>
      $(document).ready(function(){
        $(".save-comment").on('click',function(){
            var _answerid=$(this).data('answer');
            var _comment=$(".comment-text-"+_answerid).val();
            $.ajax({
                url:"/save-comment",
                type:"post",
                data:{
                    comment:_comment,
                    answerid:_answerid,
                    csrfmiddlewaretoken:"{{csrf_token}}"
                },
                dataType:'json',
                beforeSend:function(){
                    $(".save-comment").addClass('disabled').text('saving...');
                },
                success:function(res){
                    if(res.bool==true){
                        $(".comment-text-"+_answerid).val('');
                        var _html= '<div class="card mb-2 animate__animated animate__bounce">\
                                     <div class="card-body">\
                                     <p>'+_comment+'</p>\
                                     <p><a href="#">{{request.user}}</a></p>\
                                     </div>\
                                    </div>';
                    $(".comment-wrapper-"+_answerid).append(_html);
                    var prevCount=$(".comment-count-"+_answerid).text();
                    $(".comment-count-"+_answerid).text(parseInt(prevCount)+1);
                    }
                    $(".save-comment").removeClass('disabled').text('Submit');
                }
            });
        });

        $(".upvote-click").on('click',function(){
            var _answerid=$(this).data('answer');
            $.ajax({
                url:"/save-upvote",
                type:"post",
                data:{
                    answerid:_answerid,
                    csrfmiddlewaretoken:"{{csrf_token}}"
                },
                dataType:'json',
                success:function(res){
                    var _prevupvote=$(".upvote-count-"+_answerid).text();
                    if(res.bool==true){
                        $(".upvote-count-"+_answerid).text(parseInt(_prevupvote)+1);
                    }
                }
            });
        });

        $(".downvote-click").on('click',function(){
            var _answerid=$(this).data('answer');
            $.ajax({
                url:"/save-downvote",
                type:"post",
                data:{
                    answerid:_answerid,
                    csrfmiddlewaretoken:"{{csrf_token}}"
                },
                dataType:'json',
                success:function(res){
                    var _prevupvote=$(".downvote-count-"+_answerid).text();
                    if(res.bool==true){
                        $(".downvote-count-"+_answerid).text(parseInt(_prevupvote)+1);
                    }
                }
            });
        });
    });
    var ans =1;
    function show(){
        if(ans==1)
        {
            document.getElementById("answ").style.display="inline";
            return ans=0;
        }
        else{
            document.getElementById("answ").style.display="none";
            return ans=1;
        }
    }
    
    function submitformans(){
        var frm = document.getElementsByName('ansquesform')[0];
        frm.submit();
        frm.reset();
        return false;
    }
    if ( window.history.replaceState ) {
        window.history.replaceState( null, null, window.location.href );
    }
  </script>
{% endblock %}

Q&A/athreg/templates/tag.html
{% extends 'main.html' %}
{% load static %}
{% load humanize %}
{% block title %}{{tag}}{% endblock %}
{% block content %}
    <!-- Question List -->
    <div class="container py-5">
        {% for quest in quests %}
        <div class="card mb-3">
            <div class="card-body">
                <h4 class="card-title"><a href="/detail/{{quest.id}}">{{quest.q_title}}</a></h4>
                <p class="card-text">{{quest.detail}}</p>
                <p>
                    <a href="#" class="mr-2">{{quest.user.username}}</a>
                    <a href="#" class="mr-2">{{quest.answer_set.count}} Answers</a>
                    <a href="#" class="mr-2">{{quest.total_comments}} Comments</a>
                </p>
            </div>
        </div>
        {% endfor %}
    </div>
    {% if quests.has_other_pages %}
    <!-- Pagination -->
    <nav class="my-3 container">
        <ul class="pagination">
            {% if quests.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{quests.previous_page_number}}">Previous</a></li>
          {% endif %}
          {% for i in quests.paginator.page_range %}
          {% if quests.number == i %}
          <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
          {% else %}
          <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
          {% endif %}
          {% endfor %}
          {% if quests.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{quests.next_page_number}}">Next</a></li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
{% endblock %}
© 2021 GitHub, Inc.

Q&A/athreg/templates/tags.html
{% extends 'base.html' %}
{% load static %}
{% block title %}All Tags{% endblock %}
{% block content %}
    <!-- Question List -->
    <div class="container py-5">
        <div class="row">
            {% for tag in tags %}
            <div class="col-2">
                <div class="card">
                    <div class="card-body">
                        <p class="card-text"><a href="/tag/{{tag.name|slugify}}">{{tag.name}} 
                            <span class="badge badge-info">{{tag.count}}</span></a></p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}